// <auto-generated />
using System;
using CaraNegra.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaraNegra.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CaraNegra.Domain.Entities.Articulo", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArticuloId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArticuloId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Crema", b =>
                {
                    b.Property<int>("CremaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CremaId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("CremaId");

                    b.ToTable("Cremas");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Descuento", b =>
                {
                    b.Property<int>("Descuentoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Descuentoid"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EsPorcentaje")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Descuentoid");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.DetalleDescuento", b =>
                {
                    b.Property<int>("DetalleDescuentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetalleDescuentoId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Descuentoid")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleDescuentoId");

                    b.HasIndex("Descuentoid");

                    b.HasIndex("PedidoId");

                    b.ToTable("DetallesDescuento");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("DetallePedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DetallePedidoId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstadoDetallePedido")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetallePedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("NumeroMesa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MesaId");

                    b.HasIndex("NumeroMesa")
                        .IsUnique();

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MetodoPagoId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MetodoPagoId");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.MovimientoArticulo", b =>
                {
                    b.Property<int>("MovimientoArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MovimientoArticuloId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("File")
                        .HasColumnType("longtext");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenciaCod")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MovimientoArticuloId");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosArticulo");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AnuladoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AnuladoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EstaAnulado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PagoId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstadoPedido")
                        .HasColumnType("int");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PedidoId");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RolId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EsVerificado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAccesoEn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Articulo", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.DetalleDescuento", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Descuento", "Descuento")
                        .WithMany("DetallesDescuentos")
                        .HasForeignKey("Descuentoid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaraNegra.Domain.Entities.Pedido", "Pedido")
                        .WithMany("DetallesDescuentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Descuento");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaraNegra.Domain.Entities.Producto", "Producto")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.MovimientoArticulo", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Articulo", "Articulo")
                        .WithMany("MovimientosArticulos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaraNegra.Domain.Entities.Usuario", "Usuario")
                        .WithMany("MovimientosArticulos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Pago", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaraNegra.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaraNegra.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Producto", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("CaraNegra.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Articulo", b =>
                {
                    b.Navigation("MovimientosArticulos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Descuento", b =>
                {
                    b.Navigation("DetallesDescuentos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("DetallesDescuentos");

                    b.Navigation("DetallesPedidos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetallesPedidos");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CaraNegra.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("MovimientosArticulos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
